/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package app

class App {
    val greeting: String
        get() {
            return  "     _       _                               _    ____ _        \n" +
                    "    / \\   __| |_   ____ _ _ __   ___ ___  __| |  / ___(_)_   __ \n" +
                    "   / _ \\ / _` \\ \\ / / _` | '_ \\ / __/ _ \\/ _` | | |   | \\ \\ / / \n" +
                    "  / ___ \\ (_| |\\ V / (_| | | | | (_|  __/ (_| | | |___| |\\ V /  \n" +
                    " /_/   \\_\\__,_| \\_/ \\__,_|_| |_|\\___\\___|\\__,_|  \\____|_| \\_/   \n" +
                    "                                                                "
        }
}

fun main() {
    println(App().greeting)
}
